# Generated by Django 5.1.2 on 2024-10-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorPedidos',
            fields=[
                ('numero_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Realizado')], default='P', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
